import { businessGuidanceType } from './BusinessGuidance'
import { challengesAddressedType } from './ChallengesSection'
import { consultationCTAType } from './ConsultationCTA'
import { keyServices } from './ConsultingKeyServices'
import { demandDrivenFAQType } from './DemandDrivenFAQ'
import { demandDrivenImpact } from './DemandDrivenImpact'
import { empowermentType } from './Empowerment'
import { faqType } from './FAQ'
import { featuresType } from './FeaturesGrid' 
import {headingType} from './Headings'
import { productType } from './ProductSection'
import  serviceType  from './ServiceScroller'
import {cardType} from './cards'
import {loyaltyManagementServiceCards} from './LoyaltyManagementServiceCards'
import { LoayltyManagementkeyIssuesType } from './LoyaltyManagementKeyIssues'
import { loyaltyManagementProcessSteps } from './LoyaltyManagementProcess'
import { loyaltyIndustries } from './LoyaltyManagementIndustries'
import { productFeaturesType } from './ProductFeatures'
import { mobileFeaturesTypes } from './MobileProductContent'
import { showcaseContentTypes } from './ShowacaseContent'
import { productAdditionalFeatures } from './ProductAddiotionalFeatures'
import { aboutDualData } from './AboutPageDualSection'
import  leadershipTeam  from './AboutTeamSection'
import { clientsType } from './Clients'
import { heroBannerSections } from './HeroBannersSections'
import { faqSection } from './FAQSections'
import post from './Post'
import author from './Author'
import blockContent from './BlockContent'
import { dynamicProductPageType } from './dynamicProductPage'
import { dynamicServicePageType } from './dynamicServicePage'
import { dynamicConsultingsPageType } from './dynamicConsultingsPage'
import homePage from './homePage'
import about from './about'
import contact from './contact'
import { caseStudyType } from './caseStudy.ts'
import { solutionType } from './solution.ts'
import testimonialSection from './testimonialSection.ts'
import { productDropdownType } from './productDropwdown'
import { serviceDropdownType } from './serviceDropdown'
import { consultingDropdownType } from './consultingDropdown.ts'
import industries from './industries'
import { productBlogType } from './productBlog'

export const schemaTypes = [ 
    clientsType , post , author , blockContent  , dynamicServicePageType , dynamicProductPageType , homePage,      
    about , contact , caseStudyType , solutionType , serviceDropdownType , industries, productBlogType
]